version: '3.8'

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network

  # Servicio de API (backend)
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/viajes?authSource=admin
      - PORT=5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: